<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ExamScoreServerLauncher</AssemblyName>
    <RootNamespace>ExamScoreServer</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <LangVersion>7.3</LangVersion>
    <!-- 单文件，避免生成多余资源 -->
    <StartupObject>ExamScoreServer.Program</StartupObject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ServerLauncher.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>
